"""Original, hand-written one-to-two-sentence descriptions, keyed by WOD `id`.

Same policy as the movement DESCRIPTIONS in build_movements.py: never copied from
CrossFit.com, WODwell, or any other glossary — what the workout is and the
structural detail that distinguishes it, in this dataset's factual, non-editorial
tone. Every build_*.py script's `w()` helper looks a WOD's `id` up here and sets
`description` from it (falling back to null if not yet written).

Filled in batches, one category at a time — see ROADMAP.md for progress.
"""

DESCRIPTIONS = {
    # Girls
    "angie": "A bodyweight ladder of four gymnastics and core staples — 100 reps each of pull-ups, push-ups, sit-ups, and air squats, done straight through in that order for time.",
    "barbara": "Five rounds of the same bodyweight quartet as Angie at lower per-round volume, with a mandatory three-minute rest between rounds — the rest windows are part of the prescription, not just recovery.",
    "chelsea": "A 30-minute EMOM of a small pull-up, push-up, and air-squat triplet, testing whether an athlete can hold pace and quality for a full half hour rather than sprint a shorter piece.",
    "cindy": "A 20-minute AMRAP of the classic pull-up, push-up, and air-squat triplet at 5-10-15 reps per round — one of the most commonly used benchmarks for tracking bodyweight conditioning over time.",
    "diane": "A 21-15-9 couplet pairing heavy deadlifts with handstand push-ups — two very different skill demands, raw posterior-chain strength and inverted pressing, under the same descending rep scheme as Fran.",
    "elizabeth": "A 21-15-9 couplet of squat cleans and ring dips at a fixed barbell load, pairing a full-body Olympic lift with a gymnastics ring skill.",
    "fran": "The best-known CrossFit benchmark: a 21-15-9 couplet of thrusters and pull-ups, prized for being short, simple to understand, and brutally unforgiving of an overly aggressive early pace.",
    "grace": "30 clean and jerks for time at a fixed barbell weight — a single-movement sprint that rewards efficient barbell cycling under fatigue.",
    "helen": "Three rounds of a 400m run, kettlebell swings, and pull-ups — a running-based interval piece that tests grip and shoulder endurance on top of aerobic capacity.",
    "isabel": "30 snatches for time at a fixed barbell weight — Grace's more technical cousin, trading raw speed for the added skill demand of the snatch's overhead catch.",
    "jackie": "A single round of a 1000m row, 50 thrusters, and 30 pull-ups — a rowing-led triplet that front-loads a long aerobic piece before the barbell and gymnastics work.",
    "karen": "150 wall-ball shots for time at a fixed target height and load — a single-movement volume test of shoulders, legs, and mental pacing.",
    "linda": "A three-lift descending ladder (10 down to 1 reps) across deadlift, bench press, and clean, each loaded relative to the athlete's own bodyweight rather than a fixed number.",
    "mary": "A 20-minute AMRAP of handstand push-ups, alternating pistols, and pull-ups — three advanced gymnastics skills combined, making it one of the more technically demanding Girl AMRAPs.",
    "nancy": "Five rounds of a 400m run paired with overhead squats — combines running-based conditioning with an overhead-stability barbell movement performed under fatigue.",
    "annie": "A descending double-under and sit-up ladder (50-40-30-20-10) — the jump-rope analog to Fran's barbell-and-gymnastics couplet, testing coordination as much as conditioning.",
    "eva": "Five rounds of an 800m run, heavy kettlebell swings, and pull-ups — a longer-format sibling of Helen, with roughly double the running and kettlebell volume per round.",
    "kelly": "Five rounds of a 400m run, box jumps, and wall-ball shots — a running-anchored triplet pairing two lower-body-dominant movements with the run.",
    "lynne": "Five rounds of max-rep bodyweight bench press and max-rep pull-ups, scored by total reps rather than time — a strength-endurance test rather than a conditioning sprint.",
    "nicole": "A 20-minute AMRAP of a 400m run and max-rep pull-ups, scored by rounds plus total pull-up reps — pull-up capacity becomes the limiting factor as fatigue accumulates.",
    "amanda": "A descending 9-7-5 couplet of ring muscle-ups and squat snatches at a fixed heavy barbell load — one of the higher-skill Girl WODs, pairing two advanced movements at low but taxing volume.",
    "gwen": "A touch-and-go clean and jerk load test across three descending sets (15-12-9), using the same self-selected weight for every rep — scored by load rather than time, rewarding barbell efficiency under fatigue.",
    "marguerita": "50 reps each of five bodyweight movements — burpees, push-ups, jumping jacks, sit-ups, and handstands — done straight through in order for time.",
    "candy": "Five rounds of pull-ups, push-ups, and air squats at higher per-round volume than Barbara, with no prescribed rest between rounds.",
    "maggie": "Five rounds of handstand push-ups, pull-ups, and alternating pistols at escalating per-movement volume — a gymnastics-heavy sibling of Mary, compressed into a fixed five-round interval rather than an open AMRAP.",
    "hope": "Five one-minute stations — burpees, power snatches, box jumps, thrusters, and chest-to-bar pull-ups — repeated for three rounds with a minute of rest between rounds, following the same station format as Fight Gone Bad.",
    "grettel": "Ten rounds of three clean and jerks and three burpees over the bar — a short-interval couplet that repeats a small barbell and bodyweight pairing many times rather than escalating volume.",
    "ingrid": "Ten rounds of three snatches and three burpees over the bar — Grettel's snatch-based counterpart, the same rep and round scheme built around the more technical lift.",
    "barbara-ann": "Five rounds of handstand push-ups, deadlifts, sit-ups, and double-unders, with a mandatory three-minute rest between rounds — a four-movement update to Barbara's rest-interval format.",
    "lyla": "A descending 10-to-1 couplet of muscle-ups and bodyweight-relative clean and jerks, structurally similar to Linda but built around gymnastics and Olympic lifting rather than powerlifting-style strength.",
    "ellen": "Three rounds of burpees, dumbbell snatches, and dumbbell thrusters — a dumbbell-only triplet in the mold of Fran's couplet, extended to three movements.",
    "andi": "100 reps each of hang power snatch, push press, sumo deadlift high pull, and front squat at one fixed light barbell weight — a high-volume single-load barbell chipper.",
    "lane": "Five rounds of max-rep hang power snatches at a bodyweight-relative load and max-rep handstand push-ups, scored by total reps — pairs a loaded pull with strict overhead gymnastics.",

    # Heroes
    "abbate": "Two mile-long runs bookending a middle 800m run, broken up by two sets of 21 heavy clean and jerks — a running-heavy chipper with the barbell work sandwiched in the middle.",
    "adambrown": "Two rounds of a seven-movement, 24-rep circuit — deadlift, box jump, wall-ball, bench press, box jump, wall-ball, and clean — a broad full-body strength-and-conditioning sweep repeated twice.",
    "adrian": "Seven rounds of an ascending four-movement combo — 3 forward rolls, 5 wall climbs, 7 toes-to-bar, and 9 box jumps — repeated as a fixed circuit rather than building further each round.",
    "alexander": "Five rounds pairing a high-rep, moderate-load back squat with a lower-rep, heavier power clean.",
    "andy": "A mirrored chipper — thrusters, box jumps, and deadlifts building in volume toward a 1.5-mile run at the midpoint, then unwinding back through the same movements in reverse.",
    "arnie": "A single-kettlebell chipper of Turkish get-ups, overhead squats, and swings, alternating arms across the get-up and squat portions, all at one fixed weight throughout.",
    "artie": "A 20-minute AMRAP built on the classic pull-up, push-up, and air-squat triplet with an added second pull-up set and a thruster finisher each round.",
    "badger": "Three rounds of 30 squat cleans, 30 pull-ups, and an 800m run — a high-volume triplet with the run as a substantial aerobic buffer between rounds.",
    "barraza": "An 18-minute AMRAP of a 200m run, 9 heavy deadlifts, and 6 burpee bar muscle-ups — pairing a demanding gymnastics movement with heavy pulling.",
    "bell": "Three rounds of a descending-rep barbell-and-gymnastics triplet — 21 deadlifts, 15 pull-ups, and 9 front squats — at the same barbell weight for both lifts.",
    "bert": "A mirrored bodyweight pyramid of burpees, push-ups, walking lunges, and air squats, with a 400m run breaking up every movement on the way out and back.",
    "big-sexy": "Five rounds of a six-movement descending-rep circuit — heavy deadlifts and burpees, then cleans and chest-to-bar pull-ups, then thrusters and muscle-ups — getting more technical and lower-rep as it goes.",
    "blake": "Four rounds of overhead plate lunges, box jumps, wall-ball shots, and handstand push-ups — a lower-body-heavy circuit that finishes each round with strict gymnastics.",
    "bowen": "Three rounds of an 800m run followed by heavy deadlifts, burpee pull-ups, single-arm kettlebell thrusters, and box jumps — a running-anchored circuit with a long, varied tail.",
    "bradshaw": "Ten rounds of a short combo — 3 handstand push-ups, 6 deadlifts, 12 pull-ups, and 24 double-unders — repeated as a fixed circuit rather than building further.",
    "brehm": "A single-round chipper of rope climbs, heavy back squats, handstand push-ups, and a rowing calorie finisher.",
    "brian": "Three rounds pairing rope climbs with a substantial back squat set — a simple but demanding gymnastics-and-strength couplet.",
    "bruck": "Four rounds of a 400m run followed by 24 back squats and 24 jerks — a running-anchored barbell couplet at fairly high rep counts for both lifts.",
    "bulger": "Ten rounds of a short 150m run, 7 chest-to-bar pull-ups, 7 front squats, and 7 handstand push-ups — the same small combo repeated at a high round count.",
    "bull": "Two rounds of 200 double-unders, 50 overhead squats, 50 pull-ups, and a mile run — a high-volume, mixed-modal round repeated twice.",
    "buriak": "A 20-minute AMRAP of squat cleans, bar-facing burpees, pull-ups, and a 200m run — a four-movement circuit built for sustained pacing rather than a short sprint.",
    "cameron": "A ten-movement chipper alternating higher-rep bodyweight work with lower-rep gymnastics skills, finishing on rope climbs.",
    "capoot": "A descending push-up ladder (100 down to 25) paired with an ascending run distance after each set — the reps get easier as the runs get longer.",
    "chad1000x": "1,000 weighted box step-ups performed wearing a ruck — a single-movement volume test with no other movements involved.",
    "clovis": "A 10-mile run combined with 150 burpee pull-ups, partitioned however the athlete chooses — an endurance-first chipper with a large gymnastics finisher.",
    "coe": "Ten rounds of 10 thrusters and 10 ring push-ups — a barbell-and-gymnastics couplet repeated at high round count.",
    "coffey": "A descending back squat and bench press ladder (50-35-20) with an 800m run before each set, finishing with a single muscle-up after the last run.",
    "collin": "Six rounds of a sandbag carry followed by push press, box jumps, and sumo deadlift high pulls — an odd-object carry leading into a barbell-and-jump circuit.",
    "crain": "Two rounds of a seven-movement circuit — push-ups, deadlifts, box jumps, clean and jerks, burpees, wall-ball shots, and pull-ups — with a short sprint after every single movement.",
    "dae-han": "Three rounds of an 800m run carrying an empty barbell, followed by rope climbs and heavy thrusters.",
    "daniel-ray": "Five rounds of an eight-movement double-kettlebell circuit with reps climbing from 8 up to 30 across the round, closing with a 400m run each time.",
    "daniel": "A symmetric chipper bookended by 50 pull-ups, with a longer middle run and two sets of 21 thrusters framing it.",
    "danny": "A 20-minute AMRAP of box jumps, push press, and pull-ups — a straightforward three-movement circuit built for sustained pacing.",
    "del": "A symmetric chipper of burpees, weighted pull-ups, handstand push-ups, and chest-to-bar pull-ups, with a medicine-ball-carry run separating every movement.",
    "desforges": "Five rounds of a four-movement circuit, alternating a heavy lift with a higher-rep bodyweight movement each time.",
    "dg": "A 10-minute AMRAP of toes-to-bar, dumbbell thrusters, and dumbbell walking lunges — a short, dumbbell-centered triplet.",
    "dobogai": "Seven rounds pairing muscle-ups with a farmers carry — a gymnastics-and-grip couplet repeated at high round count.",
    "donny": "A deadlift-and-burpee couplet that descends 21-15-9 and then climbs straight back up to 21 — a mirrored ladder rather than a one-way descent.",
    "dork": "Six rounds of double-unders, kettlebell swings, and burpees — a jump-rope-anchored triplet at descending volume per movement.",
    "dt": "Five rounds of a descending 12-9-6 barbell triplet — deadlift, hang power clean, and push jerk — all at the same fixed weight, so the bar never leaves the hands between movements within a round.",
    "dunn": "A 19-minute AMRAP of muscle-ups, a short shuttle sprint, and burpee box jump-overs performed without touching the box.",
    "erin": "Five rounds of dumbbell split cleans and pull-ups — a two-movement couplet pairing a single-dumbbell Olympic-lift variant with high-rep pull-ups.",
    "falkel": "A 25-minute AMRAP of handstand push-ups, box jumps, and a single rope climb each round — a longer-format gymnastics-heavy triplet.",
    "feeks": "An ascending ladder (2 up to 16) of 100m shuttle sprints paired with dumbbell squat clean-thrusters at matching rep counts each round.",
    "forrest": "Three rounds of l-pull-ups, toes-to-bar, and burpees at escalating volume, capped with an 800m run each round.",
    "fournier": "A chipper of shoulder-to-overhead, burpees, and sumo deadlift high pulls, broken up by three heavy arm-over-arm sled pulls.",
    "gallant": "A descending run-and-burpee-pull-up ladder — each run is carried with a medicine ball, and both the run distance and burpee pull-up count halve at each stage.",
    "garrett": "Three rounds of high-rep air squats followed by ring handstand push-ups and l-pull-ups — a squat-heavy round leading into two strict gymnastics movements.",
    "gator": "Eight rounds pairing a low-rep, heavy front squat with a high-rep ring push-up set.",
    "gaza": "Five rounds of a descending-rep four-movement circuit — kettlebell swings, push-ups, pull-ups, and box jumps — each capped with a full mile run.",
    "glen": "A chipper of 30 clean and jerks, 10 rope climbs, and 100 burpees, with a mile run separating each pair of movements.",
    "griff": "A pure running chipper alternating 800m forward runs with 400m backward runs, repeated twice.",
    "gunny": "Three weighted mile runs bookending two rounds of push-ups and sit-ups.",
    "hamilton": "Three rounds of a 1000m row and a 1000m run, each followed by 50 reps of push-ups or pull-ups — pairing two different monostructural pieces with bodyweight work.",
    "hansen": "Five rounds of 30 kettlebell swings, 30 burpees, and 30 GHD sit-ups — a straightforward high-rep triplet.",
    "holleyman": "Thirty rounds of a small descending combo — 5 wall-ball shots, 3 handstand push-ups, and 1 power clean — a far higher round count than a typical interval WOD, testing consistency over raw output per round.",
    "hollywood": "A chipper bookended by 2000m runs, with wall-ball shots separating a muscle-up set from a heavy power clean set in the middle.",
    "hoover": "Eight rounds of a 400m run, burpee box jump-overs, a bike-erg calorie piece, and heavy alternating dumbbell snatches.",
    "hortman": "A 45-minute AMRAP of an 800m run, 80 air squats, and 8 muscle-ups — one of the longer-format Hero WODs, built for sustained output rather than a short, intense round.",
    "jack": "A 20-minute AMRAP of push press, kettlebell swings, and box jumps — a simple three-movement circuit at even reps throughout.",
    "jared": "Four rounds of an 800m run followed by high-rep pull-ups and push-ups — a running-anchored bodyweight couplet.",
    "jason": "A mirrored ladder pairing descending air-squat volume with ascending muscle-up volume — the squats get easier as the muscle-ups get harder.",
    "jbo": "A 28-minute AMRAP of overhead squats and bench press at one fixed barbell weight — a long-format couplet pairing an overhead-stability movement with horizontal pressing.",
    "jennifer": "A 26-minute AMRAP of pull-ups, kettlebell swings, and box jumps — a long-format triplet at ascending reps across the three movements.",
    "jenny": "A 20-minute AMRAP of overhead squats, back squats, and a 400m run — a light-barbell squat couplet paired with running.",
    "jerry": "Two mile runs bookending a 2000m row — a pure monostructural piece with no barbell or gymnastics work at all.",
    "johnson": "A 20-minute AMRAP of heavy deadlifts, muscle-ups, and squat cleans — combining two demanding barbell lifts with a gymnastics skill.",
    "jorge": "A descending couplet of GHD sit-ups and squat cleans, the sit-ups dropping by 6 and the cleans by 3 each round.",
    "josh": "A descending 21-15-9 overhead squat ladder paired with double the pull-up reps at each step.",
    "joshie": "Three rounds of single-arm dumbbell snatches, alternating arms each round, paired with l-pull-ups.",
    "jt": "A 21-15-9 triplet of handstand push-ups, ring dips, and push-ups — three different pressing variations at the same classic descending scheme as Fran.",
    "justin": "A 30-20-10 triplet of back squat, bench press, and strict pull-up — three foundational strength movements at a shared descending rep scheme.",
    "k27": "Twenty-seven rounds of a short hang power clean, burpee, and double-under combo — an unusually high round count that turns a small circuit into a long grind.",
    "kelly-brown": "Five rounds of a 440m row followed by box jumps, heavy deadlifts, and wall-ball shots.",
    "kevin": "Three rounds of heavy deadlifts, hanging hip touches, and a long running farmers carry.",
    "klepto": "Four rounds of box jumps, burpees, and squat cleans — a descending-rep bodyweight-to-barbell circuit.",
    "kutschbach": "Seven rounds pairing a back squat set with a jerk set at nearly matching reps — a straightforward two-lift barbell circuit repeated often.",
    "larry": "A six-step descending ladder (21 down to 3, by threes) of front squats and bar-facing burpees.",
    "ledesma": "A 20-minute AMRAP of parallette handstand push-ups, toes-to-rings, and medicine-ball cleans — an ascending-rep gymnastics-heavy triplet.",
    "lee": "Five rounds of a running-led circuit finishing with a single heavy deadlift, three squat cleans, five push jerks, three muscle-ups, and a rope climb — a broad, low-rep, high-skill combination.",
    "liam": "A chipper bookended by plate-carry runs, with high-rep toes-to-bar, heavy front squats, and rope climbs in between.",
    "loredo": "Six rounds of air squats, push-ups, and walking lunges, each round closing with a 400m run.",
    "luce": "Three rounds of a 1000m run, 10 muscle-ups, and 100 air squats — a running-anchored round with a large air-squat volume alongside a gymnastics skill.",
    "lumberjack-20": "A seven-movement chipper — deadlift, kettlebell swing, overhead squat, burpee, chest-to-bar pull-up, box jump, and dumbbell squat clean, all at 20 reps — with a 400m run after every single movement.",
    "manion": "Seven rounds of a 400m run followed by 29 back squats — a running-and-squat couplet repeated at high round count.",
    "marco": "Three rounds of a descending 21-15-9 gymnastics-and-barbell triplet — pull-ups, handstand push-ups, and thrusters — following the same scheme as Fran but with an added strict gymnastics movement.",
    "marston": "A 20-minute AMRAP built around a single very heavy deadlift rep each round, paired with toes-to-bar and bar-facing burpees.",
    "matt-16": "Three rounds of a 16-rep barbell triplet — deadlift, hang power clean, and push press — each round finishing with an 800m run.",
    "maupin": "Four rounds of an 800m run followed by 49 reps each of push-ups, sit-ups, and air squats — an unusual rep count shared evenly across three bodyweight movements.",
    "maxton": "Thirteen rounds of strict pull-ups, box step-ups, and burpees — a high round count that turns a modest per-round combo into a long grind.",
    "mccluskey": "Three rounds of an ascending gymnastics ladder — 9 muscle-ups, 15 burpee pull-ups, and 21 pull-ups — each round closing with an 800m run.",
    "mcghee": "A 30-minute AMRAP of heavy deadlifts, push-ups, and box jumps — a long-format triplet at modest, uneven rep counts.",
    "meadows": "A rings-only chipper of ascending volume — muscle-ups, slow ring lowers, ring handstand push-ups, ring rows, and ring push-ups — testing a full range of gymnastics-ring strength.",
    "michael": "Three rounds of an 800m run followed by back extensions and sit-ups — a running-and-core couplet.",
    "miron": "Five rounds of an 800m run followed by bodyweight-relative back squats and deadlifts — both barbell lifts are scaled to the athlete's own bodyweight rather than a fixed number.",
    "monti": "Five rounds of two loaded barbell step-up sets bookending a clean set and a snatch set — a step-up-heavy circuit built around two different Olympic lifts.",
    "moon": "Seven rounds alternating single-arm dumbbell hang split snatches between arms, each set followed by a rope climb.",
    "moore": "A 20-minute AMRAP of a rope climb and a 400m run, finishing each round with as many handstand push-ups as possible before starting over.",
    "morrison": "A descending 50-40-30-20-10 triplet of wall-ball shots, box jumps, and kettlebell swings.",
    "mr-joshua": "Five rounds of a 400m run, GHD sit-ups, and heavy deadlifts.",
    "murph": "A mile run bookending 100 pull-ups, 200 push-ups, and 300 air squats, traditionally performed in a weighted vest and often partitioned into rounds of 5-10-20 — one of the most widely recognized Hero WODs.",
    "nate": "A 20-minute AMRAP of muscle-ups, handstand push-ups, and kettlebell swings — a compact, gymnastics-heavy triplet at low, even reps.",
    "ned": "Seven rounds of a bodyweight-relative back squat set followed by a 1000m row — a squat-and-rowing couplet repeated at high round count.",
    "nick": "Twelve rounds of dumbbell hang squat cleans and handstand push-ups performed on the dumbbells themselves for added instability.",
    "nickman": "Ten rounds of a farmers carry, weighted pull-ups, and alternating dumbbell power snatches — a grip-and-pulling-heavy circuit at high round count.",
    "nutts": "An ascending chipper — 10 handstand push-ups up through 200 double-unders — finishing with a plate-carry run.",
    "oda-7313": "Seven rounds of a jogging run, single-arm dumbbell thrusters split between arms, and strict pull-ups.",
    "omar": "An ascending couplet of thrusters and bar-facing burpees, climbing from 10 and 15 reps up to 30 and 35.",
    "ozzy": "Seven rounds of deficit handstand push-ups followed by a 1000m run — a strict gymnastics-and-running couplet.",
    "paul": "Five rounds of double-unders, knees-to-elbows, and a heavy overhead walk — pairing jump-rope and core work with a loaded carry.",
    "pheezy": "Three rounds of a six-movement circuit alternating a heavy low-rep barbell lift with a higher-rep bodyweight movement, three times over.",
    "pike": "Five rounds of thrusters, strict ring dips, push-ups, strict handstand push-ups, and a bear crawl — combining loaded barbell work with several strict gymnastics holds.",
    "rahoi": "A 12-minute AMRAP of box jumps, thrusters, and bar-facing burpees — a short, fast triplet.",
    "ralph": "Four rounds of heavy deadlifts, burpees, rope climbs, and a 600m run.",
    "randy": "75 power snatches for time at one fixed barbell weight — a single-movement, high-volume sprint similar in spirit to Isabel but at much higher volume and a lighter load.",
    "rankel": "A 20-minute AMRAP of deadlifts, burpee pull-ups, kettlebell swings, and a 200m run — an ascending-rep four-movement circuit.",
    "rene": "Seven rounds of a 400m run followed by walking lunges, pull-ups, and burpees at descending reps.",
    "restrepo": "Five rounds of a running-led circuit combining strict pull-ups and handstand push-ups with toes-to-bar, dumbbell snatches, and a loaded dumbbell carry.",
    "ricky": "A 20-minute AMRAP of pull-ups, dumbbell deadlifts, and push press — a compact triplet mixing dumbbell and barbell loading.",
    "riley": "Two 1.5-mile runs bookending 150 burpees — a running-first chipper with one large bodyweight movement in the middle.",
    "rj": "Five rounds of an 800m run, five rope climbs, and 50 push-ups — a running-anchored gymnastics-and-bodyweight couplet.",
    "robbie": "A 25-minute AMRAP of freestanding handstand push-ups and an L-sit rope climb — two of the more advanced gymnastics skills in this dataset, paired at very low reps.",
    "rocket": "A 30-minute AMRAP of a 50-yard swim, push-ups, and air squats — one of the few Hero WODs built around swimming rather than running.",
    "roney": "Four rounds rotating through a 200m run before each of three different barbell presses — thruster, push press, and bench press — at the same weight and rep count.",
    "roy": "Five rounds of an ascending three-movement combo — 15 deadlifts, 20 box jumps, and 25 pull-ups.",
    "ryan": "Five rounds of muscle-ups and burpees — a simple two-movement gymnastics-and-bodyweight couplet.",
    "santiago": "Seven rounds of a four-movement circuit pairing dumbbell hang squat cleans and pull-ups with barbell power cleans and handstand push-ups.",
    "scotty": "An 11-minute AMRAP of heavy deadlifts, wall-ball shots, and bar-facing burpees — a short, fast triplet at odd rep counts.",
    "sean": "Ten rounds of chest-to-bar pull-ups and front squats — a two-movement couplet at high round count.",
    "severin": "A chipper of 50 strict pull-ups and 100 hand-release push-ups finishing with a 5k run — gymnastics volume up front, pure endurance at the end.",
    "sham": "Seven rounds of a bodyweight-relative deadlift set followed by a 100m sprint.",
    "ship": "Nine rounds of squat cleans and burpee box jumps — a simple couplet at high round count.",
    "sisson": "A 20-minute AMRAP of a single rope climb, 5 burpees, and a 200m run — a short, repeatable circuit built for many rounds.",
    "small": "A single-round chipper of a 1000m row, 50 burpees, 50 box jumps, and an 800m run.",
    "smykowski": "A 6k run paired with 60 burpee pull-ups — a running-heavy chipper with one demanding gymnastics movement.",
    "spehar": "A large-volume chipper of 100 heavy thrusters, 100 chest-to-bar pull-ups, and a 6-mile run, partitioned however the athlete chooses.",
    "stephen": "A four-movement descending ladder (30 down to 5) of GHD sit-ups, back extensions, knees-to-elbows, and stiff-legged deadlifts — entirely core-and-posterior-chain focused.",
    "strange": "Eight rounds of a 600m run followed by weighted pull-ups, a loaded walking lunge carrying two kettlebells, and kettlebell thrusters.",
    "t-u-p": "A descending 15-12-9-6-3 ladder alternating power cleans and front squats, with a matching set of pull-ups after each barbell movement.",
    "taylor": "Four rounds of a 400m run followed by burpee muscle-ups — a running-and-gymnastics couplet.",
    "terry": "A mirrored chipper of three mile runs framing two rounds of push-ups and bear crawls.",
    "the-don": "A ten-movement chipper at 66 reps each across deadlift, box jump, kettlebell swing, knees-to-elbows, sit-up, pull-up, thruster, wall-ball, burpee, and double-under — one uniform rep scheme applied to nearly every major movement category.",
    "the-seven": "Seven rounds of seven reps each across seven different movements — handstand push-up, thruster, knees-to-elbows, deadlift, burpee, kettlebell swing, and pull-up.",
    "thompson": "Ten rounds of a rope climb starting from a seated position, a heavy back squat set, and a farmers carry.",
    "tk": "A 20-minute AMRAP of strict pull-ups, box jumps on an elevated box, and kettlebell swings.",
    "tom": "A 25-minute AMRAP of muscle-ups, heavy thrusters, and toes-to-bar — a long-format gymnastics-and-barbell triplet.",
    "tommy-v": "A descending thruster-and-rope-climb couplet (21-15-9 on the thrusters, 12-9-6 on the climbs) — the rope-climb volume drops at a different rate than the barbell work.",
    "topsy": "A 25-minute AMRAP of ring muscle-ups, thrusters, and a rowing calorie piece.",
    "triple-deuce": "A 20-minute AMRAP of four bodyweight-and-odd-object movements at 22 reps each, finishing every round with a short sprint.",
    "tully": "Four rounds of a 200m swim followed by dumbbell squat cleans — one of the few Hero WODs built around swimming.",
    "tumilson": "Eight rounds of a 200m run followed by dumbbell burpee deadlifts — a running-and-hybrid-movement couplet repeated at high round count.",
    "tyler": "Five rounds of muscle-ups and sumo deadlift high pulls — a gymnastics-and-barbell couplet.",
    "viola": "A 20-minute AMRAP of a 400m run, power snatches, pull-ups, and power cleans — combining both Olympic lift variants in one circuit.",
    "walsh": "Four rounds of burpee pull-ups and heavy back squats, finishing each round with a 200m run carrying a plate overhead.",
    "weaver": "Four rounds of an ascending pull-up progression — l-pull-ups, then chest-to-bar, then regular pull-ups — with push-ups threaded between each variation.",
    "weston": "Five rounds of a 1000m row, a farmers carry, and a single-arm overhead dumbbell waiter's walk performed on each side.",
    "white": "Five rounds of rope climbs, toes-to-bar, overhead plate lunges, and a 400m run.",
    "whitt": "Three rounds of an 800m medicine-ball-carry run followed by wall-ball shots and ball slams, all with the same medicine ball.",
    "whitten": "Five rounds of a five-movement circuit — kettlebell swings, box jumps, a 400m run, burpees, and wall-ball shots — all at 22 reps.",
    "willy": "Three rounds of three different run distances, each paired with a different movement — a heavy low-rep front squat, chest-to-bar pull-ups, and kettlebell swings.",
    "wilmot": "Six rounds of air squats and ring dips — a simple two-movement couplet at high round count.",
    "wittman": "Seven rounds of kettlebell swings, power cleans, and box jumps at even reps throughout.",
    "wyk": "Five rounds of a heavy, low-rep front squat set, rope climbs, and a plate-carry run.",
    "yeti": "A mirrored chipper of pull-ups and muscle-ups framing a single 1.5-mile run in the middle.",
    "zembiec": "Five rounds of back squats, strict burpee pull-ups, and a 400m run.",
    "zeus": "Three rounds of a seven-movement circuit — wall-ball shots, sumo deadlift high pulls, box jumps, push press, a rowing calorie piece, push-ups, and a bodyweight back squat set — one of the broadest movement spreads in the Hero collection.",
    "zimmerman": "A 25-minute AMRAP of chest-to-bar pull-ups, heavy deadlifts, and handstand push-ups — a long-format triplet at low, even reps.",

    # Open
    "open-11-1": "A 10-minute AMRAP of double-unders and power snatches — the Open's first-ever workout, pairing jump-rope volume with a moderate-load barbell lift.",
    "open-11-2": "A 15-minute AMRAP of deadlifts, push-ups, and box jumps — a straightforward three-movement circuit.",
    "open-11-3": "A 5-minute AMRAP alternating single reps of a squat clean and a jerk at one fixed barbell weight.",
    "open-11-4": "A 10-minute AMRAP of 60 bar-facing burpees, 30 overhead squats, and 10 muscle-ups — one long round rather than a fast-repeating circuit.",
    "open-11-5": "A 20-minute AMRAP of power cleans, toes-to-bar, and wall-ball shots — a longer-format triplet built for sustained pacing.",
    "open-11-6": "A 7-minute ascending-rep couplet of thrusters and chest-to-bar pull-ups, climbing by threes (3-6-9 up to 21) for as many rounds as possible.",
    "open-12-1": "A 7-minute max-effort burpee test to a target above the athlete's standing reach — a single-movement, continuous-effort workout.",
    "open-12-2": "A 10-minute ascending-load snatch ladder — three fixed sets of 30 reps at increasingly heavy weights, then max reps at the heaviest load for the remainder of the time cap.",
    "open-12-3": "An 18-minute AMRAP of box jumps, push press, and toes-to-bar.",
    "open-12-4": "A 12-minute AMRAP of high-rep wall-ball shots, double-unders, and muscle-ups — one long round rather than a fast-repeating circuit.",
    "open-12-5": "The same ascending thruster-and-chest-to-bar-pull-up couplet as 11.6, repeated as its own Open workout the following year.",
    "open-13-1": "A 17-minute workout combining a descending burpee ladder with an ascending-load snatch ladder, finishing with max snatches at the heaviest weight for any remaining time.",
    "open-13-2": "A 10-minute AMRAP of shoulder-to-overhead, deadlifts, and box jumps at one fixed barbell weight.",
    "open-13-3": "The same high-rep wall-ball, double-under, and muscle-up triplet as 12.4, reused the following year.",
    "open-13-4": "A 7-minute ascending-rep couplet of clean and jerks and toes-to-bar, climbing by threes.",
    "open-13-5": "A fast 4-minute round of 15 thrusters and 15 chest-to-bar pull-ups — the shortest time cap in this collection.",
    "open-14-1": "The same double-under-and-power-snatch AMRAP as 11.1, reused three years later.",
    "open-14-2": "Two rounds of an ascending overhead-squat and chest-to-bar pull-up couplet, each round's reps rising from 10 to 14.",
    "open-14-3": "An 8-minute workout pairing box jumps with a deadlift ladder that gets heavier at every step (10 reps up through 35, the barbell adding weight each time) rather than lighter.",
    "open-14-4": "A 14-minute descending, chipper-style AMRAP of rowing calories, toes-to-bar, wall-ball shots, cleans, and muscle-ups.",
    "open-14-5": "A six-step descending couplet (21 down to 3, by threes) of thrusters and burpees — a longer version of Fran's ladder logic.",
    "open-15-1": "A 9-minute AMRAP of toes-to-bar, deadlifts, and snatches at one fixed barbell weight.",
    "open-15-2": "The same two-round ascending overhead-squat and chest-to-bar pull-up couplet as 14.2, reused the following year.",
    "open-15-3": "A 14-minute AMRAP of muscle-ups, wall-ball shots, and double-unders.",
    "open-15-4": "An 8-minute workout pairing an ascending handstand push-up ladder with an unevenly stepped clean ladder at one fixed heavy weight.",
    "open-15-5": "A descending 27-21-15-9 couplet of rowing calories and thrusters.",
    "open-16-1": "A 20-minute AMRAP alternating overhead-lunge-and-burpee rounds with overhead-lunge-and-chest-to-bar-pull-up rounds.",
    "open-16-2": "A staged, ever-heavier squat-clean workout: each 4-minute block repeats the same toes-to-bar-and-double-under buy-in, then asks for fewer reps at a heavier clean weight, continuing only if the previous block was finished in time.",
    "open-16-3": "A 7-minute AMRAP of power snatches and bar muscle-ups.",
    "open-16-4": "A 13-minute AMRAP of four movements all set to the same high rep count — 55 deadlifts, wall-ball shots, rowing calories, and handstand push-ups.",
    "open-16-5": "The same descending thruster-and-burpee ladder as 14.5, reused as the finale two years later.",
    "open-17-1": "An ascending dumbbell snatch ladder (10 up to 50) with 15 burpee box jump-overs inserted between every set.",
    "open-17-2": "A 12-minute AMRAP alternating a dumbbell-lunge, toes-to-bar, and power-clean round with a dumbbell-lunge, bar-muscle-up, and power-clean round.",
    "open-17-3": "A staged workout pairing three-round blocks of chest-to-bar pull-ups and squat snatches, each new block trading fewer snatch reps for a heavier bar, continuing only if the prior block finished on time.",
    "open-17-4": "The same 55-rep four-movement AMRAP as 16.4, reused the following year.",
    "open-17-5": "Ten rounds of 9 thrusters and 35 double-unders within an overall 40-minute cap.",
    "open-18-1": "A 20-minute AMRAP of toes-to-bar, dumbbell hang clean-and-jerks, and a rowing-calorie finisher.",
    "open-18-2": "A two-part workout: an ascending 1-through-10 ladder of dumbbell front-rack squats and bar-facing burpees, followed by a separately scored one-rep-max clean in whatever time remains.",
    "open-18-3": "Two rounds of a four-movement circuit — overhead squats, ring muscle-ups, dumbbell snatches, and bar muscle-ups — with 100 double-unders buffering every movement.",
    "open-18-4": "A descending 21-15-9 deadlift ladder paired with handstand push-ups at one weight, then repeated at a much heavier weight paired with handstand walks instead.",
    "open-18-5": "A 7-minute ascending thruster-and-chest-to-bar-pull-up couplet, climbing by threes up to 18.",
    "open-19-1": "A 15-minute AMRAP of wall-ball shots and rowing calories, both set to 19 reps.",
    "open-19-2": "A staged, ever-heavier squat-clean workout similar to 16.2's toes-to-bar-and-double-under buy-in structure, but frontloading two clean weights into the first 8-minute block before the later blocks add just one weight each.",
    "open-19-3": "A single chipper of a long dumbbell overhead lunge, dumbbell box step-ups, strict handstand push-ups, and a matching-distance handstand walk.",
    "open-19-4": "A two-part workout: three rounds of snatches and bar-facing burpees, followed by three rounds of bar muscle-ups and bar-facing burpees.",
    "open-19-5": "A five-step descending thruster-and-chest-to-bar-pull-up ladder starting at 33 reps — a higher-volume relative of Fran's scheme.",
    "open-20-1": "Ten rounds of ground-to-overhead and bar-facing burpees.",
    "open-20-2": "A 20-minute AMRAP of dumbbell thrusters, toes-to-bar, and double-unders at low, even reps.",
    "open-20-3": "The same descending deadlift-and-handstand-push-up/walk ladder as 18.4, reused the following year.",
    "open-20-4": "A chipper alternating box jumps (later pistols) with an ascending clean-and-jerk ladder that gets heavier and lower-rep at each step.",
    "open-20-5": "A single-round chipper of muscle-ups, rowing calories, and wall-ball shots.",
    "open-21-1": "An ascending couplet of wall climbs and double-unders, both climbing through the same six-step scheme.",
    "open-21-2": "The same ascending dumbbell snatch ladder with burpee box jump-overs as 17.1, reused four years later.",
    "open-21-3": "Three back-to-back parts sharing the same front-squat-and-thruster bookends, each swapping in a harder gymnastics movement between them — toes-to-bar, then chest-to-bar pull-ups, then bar muscle-ups.",
    "open-21-4": "A one-rep-max barbell complex — deadlift into clean into hang clean into jerk — performed on the same bar without re-gripping or dropping between lifts.",
    "open-22-1": "A 15-minute AMRAP of wall climbs, dumbbell snatches, and box jump-overs.",
    "open-22-2": "A mirrored 1-to-10-and-back-down deadlift-and-bar-facing-burpee pyramid.",
    "open-22-3": "A three-part descending chipper that swaps in a harder pull-up variation and a heavier thruster load at each step.",
    "open-23-1": "The same descending five-movement chipper-style AMRAP as 14.4, reused nearly a decade later.",
    "open-23-2": "A two-part workout: an ascending-rep AMRAP of burpee pull-ups and shuttle runs, followed by a separately scored one-rep-max thruster taken from the floor.",
    "open-23-3": "A staged workout pairing wall climbs, double-unders, and an ever-heavier snatch, later swapping the wall climbs for strict handstand push-ups as the blocks continue.",
    "open-24-1": "A 21-15-9 dumbbell snatch-and-lateral-burpee-over-dumbbell couplet, performed on one arm and then repeated on the other.",
    "open-24-2": "A 20-minute AMRAP of a 300m row, deadlifts, and double-unders.",
    "open-24-3": "A two-part workout: five rounds of thrusters and chest-to-bar pull-ups at one weight, followed by five rounds of heavier thrusters and bar muscle-ups.",
    "open-25-1": "A 15-minute AMRAP with the burpee and dumbbell clean-to-overhead reps climbing by three every round, plus a fixed 30-foot walking lunge each round.",
    "open-25-2": "The same three-part descending pull-up-variation-and-thruster chipper as 22.3, reused the following year.",
    "open-25-3": "A chipper repeating wall climbs before each of four different movements — rowing, a deadlift set, a clean set, and a snatch set — bookended by matching rowing pieces.",
    "open-26-1": "A mirrored wall-ball pyramid (20-30-40-66-40-30-20) with box jump-overs, later medicine-ball box step-overs, threaded between each set.",
    "open-26-2": "Three rounds of a dumbbell lunge-and-snatch pairing, each round finishing with a harder pull-up variation — regular, then chest-to-bar, then muscle-up.",
    "open-26-3": "Three ascending-weight blocks of burpees-over-the-bar paired with cleans and thrusters, the barbell getting heavier at each stage.",

    # Quarterfinals
    "qf-21-1": "A two-part workout: three rounds of strict handstand push-ups, dumbbell hang power cleans, and double-unders, followed by three more rounds swapping in regular handstand push-ups and dumbbell shoulder-to-overhead.",
    "qf-21-2": "A descending triplet of GHD sit-ups, rope climbs, and alternating pistols.",
    "qf-21-3": "A single-round couplet of 120 wall-ball shots and 120 rowing calories.",
    "qf-21-4": "A 4-rep-max front squat test — pure strength, no conditioning component.",
    "qf-21-5": "A fast descending 9-6-3 couplet of heavy snatches and burpee box jump-overs over a tall box.",
    "qf-22-1": "A chipper pairing three different dumbbell lunge variations with three increasingly strict handstand push-up variations.",
    "qf-22-2": "Three rounds of alternating pistols, GHD sit-ups, and muscle-ups.",
    "qf-22-3": "A mirrored pyramid (up to 32 and back down) shared across wall-ball shots, shuttle runs, and rope climbs.",
    "qf-22-4": "A one-rep-max barbell complex — clean into bench press into overhead squat — on the same bar throughout.",
    "qf-22-5": "A fast triplet of rowing calories, burpee box jump-overs, and heavy snatches.",
    "qf-23-1": "A three-step ladder pairing a descending, lightening front squat with an ascending, more demanding gymnastics skill each round — handstand walks, then muscle-ups, then wall-facing handstand push-ups.",
    "qf-23-2": "A 12-minute AMRAP of dumbbell snatches and overhead lunges split evenly between arms, finishing each round with crossover single-unders.",
    "qf-23-3": "An ascending clean-and-jerk ladder (1 up to 5 reps) at one heavy fixed weight, with 5 burpee box jump-overs before every set.",
    "qf-23-4": "A 20-minute AMRAP of a long row, GHD sit-ups, a shorter row, and v-ups.",
    "qf-23-5": "A three-step descending deadlift ladder that gets heavier at each step, pairing it with an increasingly demanding gymnastics skill — chest-to-bar pull-ups, then bar muscle-ups, then rope climbs.",
    "qf-24-1": "Four one-minute max-rep stations — heavy snatches, rowing calories, and dumbbell box step-ups — each separated by a minute of rest.",
    "qf-24-2": "Three rounds of high-rep wall-ball shots and lateral burpees over a box.",
    "qf-24-3": "A chipper built almost entirely around handstand push-up variations, escalating from regular to strict to wall-facing, each paired with a different gymnastics movement.",
    "qf-24-4": "Three fixed sets of 10 clean and jerks at increasing weights, finishing with an AMRAP of clean and jerks at the heaviest weight for whatever time remains.",
    "qf-26-1": "A mirrored workout of shuttle runs, overhead squats, and burpees over the bar, performed forward and then back in reverse order.",
    "qf-26-2": "A single-round couplet of high-rep dumbbell hang squat cleans and bar muscle-ups.",
    "qf-26-3": "Six rounds of double-unders and deadlifts, with the barbell getting heavier over the final three rounds.",
    "qf-26-4": "A single-round couplet of two 1000m rows bookending a heavy clean-and-jerk set and a strict handstand push-up set.",

    # Games
    "games-07-crossfit-total": "The classic CrossFit Total benchmark (1RM back squat, press, and deadlift), used as the final event of the inaugural 2007 Games.",
    "games-07-the-hopper-workout": "A 1000m row done once, followed by five rounds of pull-ups and push jerks.",
    "games-07-trail-run": "An approximately 5k trail run — one of the simplest events in Games history, pure running with no fixed course distance published.",
    "games-08-sundays-workout": "30 clean and jerks for time at a fixed barbell weight — the classic Girl WOD Grace, reused as the final event of the 2008 Games.",
    "games-08-the-hill-run": "A steep, off-trail 750m hill run within a 20-minute cap.",
    "games-08-workout-a": "A 21-15-9 thruster-and-pull-up couplet — the classic Girl WOD Fran, reused as a Games event.",
    "games-08-workout-b": "Five rounds of heavy deadlifts and burpees within a 12-minute cap.",
    "games-09-1rm-snatch": "A one-rep-max snatch test — pure strength, no fixed Rx weight.",
    "games-09-complex-chipper": "A ten-movement chipper spanning cleans, toes-to-bar, box jumps, muscle-ups, dumbbell push press, double-unders, thrusters, pull-ups, burpees, and a weighted overhead lunge.",
    "games-09-deadlift-ladder": "A deadlift ladder adding 10 lb every 30 seconds until failure — rewards both starting strength and the ability to keep making lifts as the bar gets heavier.",
    "games-09-hill-run": "A 7k hill run — one of the longer pure-running Games events.",
    "games-09-hill-sprint-sandbags": "A hill sprint carrying sandbags — men carry two, women carry one.",
    "games-09-hspu-kb-ghd": "An 8-minute AMRAP of handstand push-ups, Russian kettlebell swings, and GHD sit-ups.",
    "games-09-row-stake": "A 500m row, a stake driven into the ground with an overhead strike, then another 500m row.",
    "games-09-wall-ball-snatch": "Three rounds of wall-ball shots and squat snatches.",
    "games-10-amanda": "A descending 9-7-5 couplet of ring muscle-ups and squat snatches — the classic Girl WOD Amanda, reused as a Games event.",
    "games-10-cleans-handstand-pushups": "Seven rounds of heavy cleans and handstand push-ups (on rings for men, on the floor for women).",
    "games-10-event-3": "Two rounds of a six-movement circuit — a short run, box jump-overs, dumbbell squat cleans, double-unders, hand-release push-ups, GHD sit-ups, and a walking lunge.",
    "games-10-max-rep-deadlift": "A one-minute max-rep deadlift test at a fixed weight, immediately preceding a separately scored max-load shoulder-to-overhead on the same clock.",
    "games-10-sandbag-move": "Carrying a heavy sandbag down the stadium stairs, across the floor, up a wall, and up the far stairs — a single-movement venue-specific carry.",
    "games-10-shoulder-to-overhead": "A one-rep-max shoulder-to-overhead test, required to be completed within 12 minutes of starting the paired Max Rep Deadlift event.",
    "games-10-the-final-1": "Three rounds of hand-release push-ups, a wall climb-over, and overhead squats — the first of three finale events.",
    "games-10-the-final-2": "Three rounds of toes-to-bar and ground-to-overhead — the second of three finale events.",
    "games-10-the-final-3": "Three rounds of a burpee wall jump and rope climbs — the third and last of the 2010 finale events.",
    "games-11-beach": "A beach event of a swim and soft-sand run bookending chest-to-bar pull-ups, hand-release push-ups, and air squats.",
    "games-11-dog-sled": "A chipper of double-unders and overhead squats followed by handstand push-ups and heavy sled pushes.",
    "games-11-killer-kage": "Three rounds of front squats, a bike ride, and a monkey-bar traverse.",
    "games-11-rope-clean": "A descending rope-climb-and-clean-and-jerk ladder (5 down to 1) with the barbell getting heavier at every step.",
    "games-11-skills-1": "Three independently scored skill tests — an L-sit hold, a softball throw for distance, and a handstand walk for distance — with the final ranking based on the sum of the three placings.",
    "games-11-skills-2": "Three more independently scored skill tests — a weighted chest-to-bar pull-up, a max-load snatch, and a weighted jug carry — again ranked by the sum of the three placings.",
    "games-11-the-end-1": "A 3-minute AMRAP of an eight-movement circuit — rowing calories, wall-ball shots, toes-to-bar, box jumps, kettlebell sumo deadlift high pulls, burpees, shoulder-to-overhead, and a sled pull.",
    "games-11-the-end-2": "The same eight-movement circuit as The End 1, extended to a 6-minute AMRAP.",
    "games-11-the-end-3": "The same eight-movement circuit as The End 1 and 2, performed once for time rather than as an AMRAP.",
    "games-11-triplet-sprint": "Four rounds of muscle-ups, deadlifts, and GHD sit-ups, each followed by a sprint that gets longer every round.",
    "games-12-ball-toss": "A seated medicine-ball throw for distance from a GHD machine.",
    "games-12-broad-jump": "Three attempts at a standing broad jump, scored by the single furthest jump.",
    "games-12-chipper": "A mirrored chipper of overhead squats, box jump-overs, thrusters on a fat bar, power cleans, toes-to-bar, and burpee muscle-ups.",
    "games-12-clean-ladder": "A clean ladder through progressively heavier barbells every 30 seconds, athletes ranked by their heaviest successful lift.",
    "games-12-double-banger": "Three rounds of double-unders finishing on a different sledgehammer-strike target each time.",
    "games-12-elizabeth": "A 21-15-9 clean-and-ring-dip couplet — the classic Girl WOD Elizabeth, reused as a Games event.",
    "games-12-fran": "The classic 21-15-9 thruster-and-pull-up couplet, reused directly as a Games event under its original name.",
    "games-12-isabel": "30 snatches for time at a fixed barbell weight — the classic Girl WOD Isabel, reused as a Games event.",
    "games-12-medball-handstand-push-up": "Three rounds of heavy medicine-ball cleans and carries paired with parallette handstand push-ups.",
    "games-12-pendleton-1": "A long-course swim, mountain bike, and trail run through undulating terrain and significant elevation gain.",
    "games-12-pendleton-2": "The same swim-bike-run course as Pendleton 1, run again as a separate scored event.",
    "games-12-rope-sled": "Five rounds of a rope climb and a heavy sled push.",
    "games-12-track-triplet": "Three rounds of split snatches, bar muscle-ups, and a 400m run.",
    "games-13-2007": "A 1000m row followed by five rounds of pull-ups and push jerks — a near-identical repeat of the 2007 Games' Hopper Workout, referencing that inaugural year directly in its name.",
    "games-13-burden-run": "A long endurance chipper of running, an over-the-shoulder object flip, a heavy log carry, and a sled drag.",
    "games-13-clean-jerk-ladder": "An elimination-style clean and jerk ladder where the athlete picks a starting weight, then must make progressively heavier singles every 90 seconds or be eliminated.",
    "games-13-legless": "A descending thruster ladder (27 down to 9) paired with a descending legless-rope-climb ladder (4 down to 1).",
    "games-13-naughty-nancy": "Four rounds of a hill run over a berm paired with heavy overhead squats.",
    "games-13-row-1": "A half-marathon row, scored at the 2,000m checkpoint split.",
    "games-13-row-2": "The same half-marathon row as Row 1, scored instead at the full finish.",
    "games-13-sprint-chipper": "A short chipper of GHD-style sit-ups, heavy snatches, and burpees to an elevated target.",
    "games-13-the-cinco-1": "Three rounds of heavy deadlifts and single-leg kettlebell pistols on each leg.",
    "games-13-the-cinco-2": "Three rounds of muscle-ups and deficit handstand push-ups.",
    "games-13-the-pool": "Ten rounds of a 25-yard swim and bar muscle-ups.",
    "games-14-21-15-9-complex": "A descending complex spanning deadlift, clean, snatch, pull-up, chest-to-bar pull-up, and bar muscle-up, all at one fixed barbell weight.",
    "games-14-double-grace": "60 clean and jerks for time at the classic Grace weight — twice the volume of the original Girl WOD.",
    "games-14-midline-march": "Three rounds of GHD sit-ups, a handstand walk, and a weighted overhead walking lunge.",
    "games-14-muscle-up-biathlon": "A descending muscle-up ladder with a 400m run before each set.",
    "games-14-overhead-squat": "A one-rep-max overhead squat test across three attempts.",
    "games-14-push-pull": "An ascending deficit handstand push-up ladder paired with an increasingly heavy sled pull.",
    "games-14-sprint-carry": "Three rounds of a 100-yard sprint and a 100-yard sandbag carry, the sandbag getting heavier each round.",
    "games-14-sprint-sled-1": "A single 100-yard heavy sled push against a 2-minute cap.",
    "games-14-sprint-sled-2": "The same 100-yard sled push as Sprint Sled 1, against a slightly longer cap.",
    "games-14-the-beach": "A mirrored chipper of ocean swims bookending kettlebell thrusters and burpees.",
    "games-14-thick-n-quick": "A fast round of rope climbs on a thick 2-inch rope paired with a heavy overhead squat.",
    "games-14-triple-3": "A single round of a 3000m row, 300 double-unders, and a 3-mile run.",
    "games-15-clean-and-jerk": "A one-rep-max clean and jerk test, contested in short lifting windows with athletes alternating turns.",
    "games-15-heavy-dt": "Five rounds of the DT barbell triplet — deadlift, hang power clean, push jerk — at a heavier weight than the original Hero WOD.",
    "games-15-midline-madness": "Six rounds of a 400m run and a heavy yoke carry.",
    "games-15-murph": "The classic Murph Hero WOD — a mile run bookending 100 pull-ups, 200 push-ups, and 300 air squats — run as a Games event under a 55-minute cap.",
    "games-15-pedal-to-the-metal-1": "A short round of pegboard ascents, rowing and biking calories, and a squat-style dumbbell snatch.",
    "games-15-pedal-to-the-metal-2": "A companion event to Pedal to the Metal 1, swapping in parallette handstand push-ups and a heavy kettlebell deadlift for the pegboard and dumbbell snatch.",
    "games-15-pier-paddle": "A swim-paddleboard-swim event along a pier.",
    "games-15-sandbag-2015": "Moving a series of heavy sandbags up stairs, across the floor, and up a wall to the top of a second staircase.",
    "games-15-soccer-chipper": "A chipper of a heavy over-the-shoulder ball flip, legless rope climbs, and an unbroken handstand walk.",
    "games-15-triangle-couplet": "A descending thruster-and-bar-muscle-up couplet (15-10-6).",
    "games-16-100-percent": "A fast couplet of box jumps and heavy D-ball cleans.",
    "games-16-climbing-snail": "Three rounds of a berm run, rope climbs, and a heavy sled push on the 'Snail' apparatus.",
    "games-16-double-dt": "Ten rounds of the DT barbell triplet — double the round count of the original Hero WOD.",
    "games-16-handstand-walk": "A single long handstand walk, required to be broken into unbroken 20-foot sections.",
    "games-16-murph": "The classic Murph Hero WOD, reused as a Games event for the second consecutive year.",
    "games-16-ocean-swim": "A 500m ocean swim starting and finishing on the beach, around two buoys.",
    "games-16-ranch-deadlift-ladder": "A one-lift-every-30-seconds deadlift ladder through a published series of ever-heavier barbells, with athletes lifting in reverse order of their finish in an earlier running event.",
    "games-16-ranch-mini-chipper": "A short chipper of wall-ball shots and GHD-style sit-ups finishing with a hill sprint carrying the medicine ball.",
    "games-16-ranch-trail-run": "A 7k trail run.",
    "games-16-redemption": "A descending thruster ladder (21-15-9) with a pegboard ascent before each set.",
    "games-16-rope-chipper": "A long machine-and-jump-rope chipper spanning the ski erg, rower, and assault bike, with weighted-rope double-unders threaded throughout and a heavy sled pull to finish.",
    "games-16-squat-clean-pyramid": "A staged, ever-heavier squat clean ladder against tightening time windows — fewer reps required at each stage, but the barbell gets significantly heavier.",
    "games-16-suicide-sprint": "A shuttle-sprint suicide run across a 280-foot course, increasing in distance each leg before a final full-length sprint.",
    "games-16-the-plow": "A single heavy sled drag on the 'Plow' apparatus.",
    "games-16-the-separator": "Three rounds trading a descending ring handstand push-up count for an ascending squat variation — back squat, then front squat, then overhead squat — with burpees between each.",
    "games-17-1rm-snatch": "A one-rep-max snatch test with extra attempts awarded to the top 10 finishers.",
    "games-17-2223-intervals": "Four rounds of one-minute-on, one-minute-off intervals combining rope climbs, ski-erg calories, and max-rep overhead squats.",
    "games-17-amanda-45": "A descending muscle-up-and-squat-snatch ladder (13-11-9-7-5) — a higher-volume, lighter-load variant of the classic Amanda.",
    "games-17-assault-banger": "A fast couplet of assault bike calories and sledgehammer strikes on the 'banger' track.",
    "games-17-fibonacci-final": "An ascending Fibonacci-sequence ladder (5-8-13) of parallette handstand push-ups and kettlebell deadlifts, finishing with a heavy overhead kettlebell lunge.",
    "games-17-heavy-17-5": "Ten rounds of thrusters and double-unders at a heavier load than the original Open workout it's named for.",
    "games-17-madison-triplet": "Five rounds of a run and a burpee that requires cleaning a sandbag over a hay-bale wall.",
    "games-17-muscle-up-clean-ladder": "Eight rounds of bar muscle-ups and heavy cleans.",
    "games-17-run-swim-run": "A mirrored run-swim-run event bookending a middle-distance swim with two 1.5-mile runs.",
    "games-17-strongmans-fear": "A mirrored strongman-style chipper of yoke carries, handstand walks, a farmers-style log carry, and a sled drag.",
    "games-17-triple-g-chipper": "A single chipper of pull-ups, GHD sit-ups, alternating pistols, rowing calories, and heavy dumbbell push press.",
    "games-18-30-muscle-ups": "30 muscle-ups for time — a single-movement volume test.",
    "games-18-aeneas": "A chipper of pegboard ascents and thrusters finishing with three ascending-weight yoke carries.",
    "games-18-bicouplet-1": "A descending 21-15-9 snatch-and-chest-to-bar-pull-up couplet.",
    "games-18-bicouplet-2": "A descending 12-9-6 snatch-and-bar-muscle-up couplet at a heavier load than Bicouplet 1.",
    "games-18-chaos": "A six-movement chipper spanning the ski erg, burpees to a target, single-arm dumbbell overhead squats, alternating pistols, box jump-overs, and a heavy sled pull.",
    "games-18-crossfit-total": "The classic CrossFit Total benchmark — 1RM back squat, strict press, and deadlift, each with three attempts inside a 4-minute window.",
    "games-18-fibonacci": "A deficit version of the Fibonacci ladder — ascending parallette handstand push-ups and kettlebell deadlifts (5-8-13), finishing with a heavy overhead kettlebell lunge.",
    "games-18-handstand-walk": "A technical handstand walk course — a pylon slalom, a ramp, stairs, and parallel bars — following a set of heavy-rope double-unders.",
    "games-18-madison-triplus": "A swim, paddleboard, and run combination.",
    "games-18-marathon-row": "A full marathon distance (42,195m) rowed for time.",
    "games-18-two-stroke-pull": "Five rounds of a run, assault bike calories, and a heavy sled pull.",
    "games-19-clean": "A one-rep-max clean test where athletes lift in reverse order of current placement, the bar getting heavier each round.",
    "games-19-first-cut": "Four rounds of a run, legless rope climbs, and heavy squat snatches — an elimination-style cut event, with only the top finishers advancing to the next round of competition.",
    "games-19-mary": "A 20-minute AMRAP of handstand push-ups, alternating pistols, and pull-ups — the classic Girl WOD Mary, reused as a Games event.",
    "games-19-ringer-1": "A descending bike-and-toes-to-ring couplet (30-20-10).",
    "games-19-ringer-2": "A descending burpee-and-overhead-squat couplet (15-10-5), the burpees finishing with a jump to touch the rings.",
    "games-19-ruck": "Four 1500m runs, each with a heavier weighted ruck than the last.",
    "games-19-second-cut": "An 800m row, a heavy double-kettlebell shoulder-to-overhead set, and a long handstand walk.",
    "games-19-split-triplet": "Five rounds of a pegboard ascent, double-unders, and a dumbbell hang split snatch immediately followed by a split-style dumbbell hang clean and jerk.",
    "games-19-sprint-couplet": "A sled-push-and-bar-muscle-up sandwich — a heavy sled push, a set of bar muscle-ups, then the same sled push again.",
    "games-19-swim-paddle": "A long swim followed by an equal-distance paddleboard leg.",
    "games-19-the-standard": "A single round of 30 clean and jerks, 30 muscle-ups, and 30 snatches at the same barbell weight.",
    "games-20-1000m-row": "A single 1000m row for time — pure monostructural testing.",
    "games-20-1rm-front-squat": "A one-rep-max front squat test.",
    "games-20-2007-reload": "Five rounds of a row, bar muscle-ups, and heavy shoulder-to-overhead — an homage to the Games' 2007 origins.",
    "games-20-atalanta": "A mirrored mile-run bookend around large volumes of handstand push-ups, alternating pistols, and pull-ups, all performed in a weighted vest.",
    "games-20-awful-annie": "A descending double-under-and-GHD-sit-up ladder (50-40-30-20-10) finishing with an ascending-weight clean ladder (5-4-3-2-1).",
    "games-20-bike-repeater": "Ten rounds of a bike interval and a legless rope climb.",
    "games-20-corn-sack-sprint": "A 320-meter hill sprint carrying a loaded sandbag.",
    "games-20-crossfit-total": "The classic CrossFit Total benchmark, repeated as a separate Games event two years after 2018's version.",
    "games-20-damn-diane": "Three rounds of heavy deadlifts and deficit strict handstand push-ups — a nod to the classic Girl WOD Diane's couplet, at higher volume and a deficit.",
    "games-20-friendly-fran": "Three rounds of thrusters and chest-to-bar pull-ups at Fran's classic 21-rep count, spread across multiple rounds rather than descending.",
    "games-20-handstand-hold": "A max-effort freestanding handstand hold within a marked box, ending on a border touch or a foot or head touching the ground.",
    "games-20-handstand-sprint": "A single 100-yard handstand walk for time.",
    "games-20-happy-star": "An ascending hill-run-burpee-thruster combination, with the run course changing and the thruster load increasing each round.",
    "games-20-nasty-nancy": "Five rounds of a run, heavy overhead squats, and bar-facing burpees — a heavier, longer relative of the classic Girl WOD Nancy.",
    "games-20-ranch-loop": "A roughly 6-mile out-and-back trail run over varied terrain.",
    "games-20-sprint-sled-sprint": "A sprint-sled-push-sprint sandwich over 100 yards each.",
    "games-20-swim-n-stuff": "Four rounds of bike calories, a short swim, GHD sit-ups, and ball slams.",
    "games-20-toes-to-bar-lunge": "A descending toes-to-bar ladder paired with a descending double-kettlebell front-rack lunge, measured by distance walked.",
    "games-21-event-1": "A one-mile fin swim followed by a 3-mile kayak.",
    "games-21-event-10": "A run-and-toes-to-bar sandwich — two 1.5-mile runs bookending three sets of toes-to-bar.",
    "games-21-event-11": "An 11-minute AMRAP of pegboard ascents, single-arm dumbbell overhead squats, and double-unders on a heavily loaded rope.",
    "games-21-event-12": "A one-rep-max snatch test with fast-paced progressive attempts, the final round contested on a single shared platform.",
    "games-21-event-13": "Four rounds of GHD sit-ups, a weighted burpee over a hay bale, and a very heavy yoke carry, against tightening time windows.",
    "games-21-event-14": "An ascending heavy-deadlift-and-freestanding-handstand-push-up ladder (6-10-14).",
    "games-21-event-15": "A single round of a short row, a large chest-to-bar pull-up set, and three different loaded walking lunge variations.",
    "games-21-event-2": "A mirrored chipper of a heavy sled push and an over-the-shoulder ball flip bookending four sets of muscle-ups and bar muscle-ups.",
    "games-21-event-3": "A single 550-yard sprint.",
    "games-21-event-4": "A mirrored descending ladder (10 down to 1) of wall climbs and heavy thrusters.",
    "games-21-event-5": "Four rounds of rope climbs, a long ski-erg piece, and a heavy husafell carry.",
    "games-21-event-6": "Five rounds of a short run and a single heavy clean.",
    "games-21-event-7": "Five rounds of a shorter run and a single very heavy clean — a heavier companion to Event 6.",
    "games-21-event-9": "A descending echo-bike-and-snatch ladder, the barbell getting heavier as the reps drop.",
    "games-22-back-nine": "A mirrored strength event of heavy yoke carries bookending front squats and a very heavy deadlift set.",
    "games-22-bike-to-work": "A long chipper of toes-to-bar and chest-to-bar pull-ups separated by two 5-mile bike legs.",
    "games-22-echo-press": "A mirrored echo-bike-and-deficit-handstand-push-up chipper.",
    "games-22-elizabeth-elevated": "A descending squat-clean-and-bar-dip couplet, the dips split into unbroken sets each starting with a parallel bar traverse — a harder variant of the classic Elizabeth.",
    "games-22-hat-trick": "Three rounds of a sprint, wall-ball shots to an elevated target, and heavy alternating dumbbell snatches, separated by long rest periods.",
    "games-22-jackie-pro": "A row, thruster, and bar-muscle-up chipper with a strict time standard on the row — a harder, bar-muscle-up version of the classic Girl WOD Jackie.",
    "games-22-rinse-n-repeat": "Eight rounds of a short swim and ski-erg calories, the calorie target climbing each round before capping out.",
    "games-22-sandbag-ladder": "A max-effort sandbag-clean ladder through progressively heavier bags until the athlete fails to lift one to the shoulder.",
    "games-22-shuttle-to-overhead": "Three escalating rounds of a run and max-rep jerks in the time remaining, the run getting longer each round.",
    "games-22-the-alpaca": "A sled-push-and-kettlebell-clean-and-jerk chipper, the sled unloading kettlebells with each pass while the barbell-free kettlebell work stays constant.",
    "games-22-the-capitol": "A long chipper of an over-the-shoulder ball flip and a 3.5-mile run, finishing with two heavy carries.",
    "games-22-up-and-over": "Three rounds of muscle-ups, a box jump-over sequence spanning a log, a box, and a raised platform, and GHD sit-ups.",
    "games-23-alpaca-redux": "A repeat of 2022's Alpaca sled-push-and-kettlebell chipper, with legless rope climbs added between rounds.",
    "games-23-cross-country-5k": "A 5k cross-country run.",
    "games-23-echo-thruster-final": "A descending echo-bike-and-thruster ladder, finishing with a heavy overhead walking lunge.",
    "games-23-helena": "Three rounds of a run, bar muscle-ups, and heavy dumbbell snatches.",
    "games-23-intervals": "Two mirrored intervals of box jump-overs, rowing calories, and burpee box jump-overs, the movement order flipped between the two.",
    "games-23-inverted-medley": "A mirrored gymnastics medley of handstand walks, freestanding handstand push-ups, and obstacle pirouettes that rotate a full 180 and then 360 degrees.",
    "games-23-muscle-up-logs": "Five rounds of muscle-ups and heavy log lifts, the log getting heavier on the final round.",
    "games-23-olympic-total": "A one-rep-max snatch and clean and jerk test, each contested in fast, short lifting windows.",
    "games-23-parallel-bar-pull": "Eight rounds of a parallel-bar traverse, heavy-rope double-unders, and a hand-over-hand sled pull.",
    "games-23-pig-chipper": "A mirrored chipper of an over-the-shoulder ball flip bookending large sets of chest-to-bar pull-ups, toes-to-bar, and wall-ball shots.",
    "games-23-ski-bag": "A descending ski-erg-and-sandbag-squat couplet.",
    "games-24-chad": "1,000 weighted box step-ups in a weight vest, completed as 250 trips up and down — one of the longest single-movement volume tests in Games history.",
    "games-24-clean-ladder": "A three-round clean ladder against tight time windows, the barbell getting heavier at every single lift within each round.",
    "games-24-dickies-triplet": "Five rounds of a short run, toes-to-bar, and heavy alternating dumbbell snatches.",
    "games-24-final-1815": "A mirrored chipper of thrusters and bar muscle-ups bookending a very heavy yoke carry.",
    "games-24-final-2421": "A descending thruster-and-chest-to-bar-pull-up couplet split around a heavy yoke carry in the middle.",
    "games-24-firestorm": "Three short rounds of echo-bike calories and burpees over an obstacle.",
    "games-24-lake-day": "A 3.5-mile run followed by an 800m open-water swim.",
    "games-24-midline-climb": "A mirrored core-and-grip chipper of heavy deadlifts, rope climbs, ski-erg calories, and GHD sit-ups.",
    "games-24-push-pull-2": "A chipper of handstand push-up variations paired with heavy sled pulls performed from standing and then seated.",
    "games-24-track-and-field": "A run followed by a separately timed shuttle event of ascending sprint-and-sandbag-carry distances.",
    "games-25-1rm-back-squat": "A one-rep-max back squat test.",
    "games-25-albany-grip-trip": "Five rounds of a run, heavy deadlifts, and a long handstand walk that gets longer on the final round.",
    "games-25-all-crossed-up": "A chipper of wall climbs, heavy dumbbell shoulder-to-overhead, crossover single-unders, and toes-to-bar, repeated across three waves.",
    "games-25-atlas": "An ascending thruster-and-rope-climb ladder finishing with a heavy overhead walking lunge.",
    "games-25-climbing-couplet": "A descending pegboard-and-squat-clean ladder, each clean immediately followed by a front squat counted as one rep of the complex, the bar getting heavier as the reps drop.",
    "games-25-going-dark": "A mirrored chipper of echo-bike calories bookending a yoke carry and deficit handstand push-ups.",
    "games-25-hammer-down": "A single round of bike calories, bar muscle-ups, and burpee box jump-overs.",
    "games-25-run-row-run": "A run-row-run sandwich covering four miles of running and a 3000m row.",
    "games-25-running-isabel": "Five rounds of a short run and heavy snatches — a running-added variant of the classic Girl WOD Isabel.",
    "games-25-throttle-up": "A single round of ski-erg calories, chest-to-bar pull-ups, and burpee box jump-overs.",
}
